---
title: "R Notebook - R Assignment BCB 546X"
output: html_notebook
---

#First I need to import the two files I will be using. To do this I will use read_delim().
#Using view() also allows me to look at the file as well.

library(readr)
fang <- read_delim("C:/Users/Stock/Desktop/BCB-546X/R_Assignment/fang_et_al_genotypes.txt", "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)
View(fang)

#There's a reason I did col_names = FALSE on the genotype file and not on the snp file next. I wanted to keep a header for the snp file, however, I did not want a header for the genotype file. The reason for this is because I will need to transpose the two separate genotype files I will need later, but need the potential header from the genotype file to be transposed and a portion of the dataset also later on. The snp file is fine as is and the header will be used later on.

library(readr)
snp <- read_delim("C:/Users/Stock/Desktop/BCB-546X/R_Assignment/snp_position.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
View(snp)

#Now I want look at the structure of both datasets using structure().
#I do this to identify similarities between the two files.

str(fang)
head(snp)

#From this I can see I have mostly character variables and some interger variables within the snp file.

#Now I want to separate out my genotype file by group type.
#I would like a file for maize only and for teosinte only.

maize <- fang[fang$X3 == "Group" | fang$X3 == "ZMMIL" | fang$X3 == "ZMMLR" | fang$X3 == "ZMMMR",]
teosinte <- fang[fang$X3 == "Group" | fang$X3 == "ZMPBA" | fang$X3 == "ZMPIL" | fang$X3 == "ZMPJA",]

#I had to keep Group in both searches, as if I didn't it would have eliminated the SNP_ID's that I will need once I transpose the data to be able to merge.

#As before to be able to merge both datasets together I need to transpose my genotype files.

t_maize <- t(maize)
head(t_maize)
t_teosinte <- t(teosinte)
head(t_teosinte)

#Now that I see the data is arranged approriately, I want to add back the column names as the first row of data and I do not want to keep the first 3 lines of the data frame from both genotype files.

colnames(t_maize) <- t_maize[1,]
t_maize <- t_maize[-1:-3,]
head(t_maize)
NROW(t_maize)

colnames(t_teosinte) <- t_teosinte[1,]
t_teosinte <- t_teosinte[-1:-3,]
head(t_teosinte)
NROW(t_teosinte)

#Now I have a snp file and two genotype files (maize and teosinte) that match in length at 983 rows and a common column between the two, but I need to rename the genotype column "Sample_ID" to match the snp file as "SNP_ID".

colnames(t_maize)[1] <- "SNP_ID"
colnames(t_teosinte)[1] <- "SNP_ID"

#Now I can merge the two files together to produce one file for maize and one file for teosinte.

maize_merged <- merge(snp, t_maize, by = "SNP_ID")
teosinte_merged <- merge(snp, t_teosinte, by = "SNP_ID")


```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
